### ISSUE TITLE
License missing from gemspec

### ISSUE THREAD

**Issue by bf4** [PeopleAdmin/resque-clues#1]
Some companies will only use gems with a certain license.
The canonical and easy way to check is [via the gemspec](http://docs.rubygems.org/read/chapter/20#license)
via e.g.

```
spec.license = 'MIT'
# or
spec.licenses = ['MIT', 'GPL-2']
```

Bundler now generates gems with a default 'MIT' license.  There is even a [License Finder](https://github.com/pivotal/LicenseFinder)
to help companies ensure all gems they use meet their licensing needs. This tool depends on license information being available in the gemspec.
Including a license in your gemspec is a good practice, in any case.

If you need help choosing a [license](http://opensource.org/licenses), github has created a [license picker tool](http://choosealicense.com/)

How did I find you?

I'm using a script to collect stats on gems, originally looking for download data, but decided to collect licenses too,
and [make issues for gemspecs not specifying a license as a public service :)](https://github.com/bf4/gemproject/issues/1)
So far it's going pretty well.
I've written a [blog post about it](http://www.benjaminfleischer.com/2013/07/12/make-the-world-a-better-place-put-a-license-in-your-gemspec/)

**Comment by mdespuits** [comment]
@lwoodson Is this something we want to add or talk about?

**Comment by joshuaflanagan** [comment]
We already have the LICENSE file in the root. We can add it to the gemspec if it matters to anyone other than the bots.

**Comment by mdespuits** [comment]
Fair enough. Is this worth closing, then?

**Comment by lwoodson** [comment]
Can be closed, thanks.  If someone real complains, we can revisit.
- L

On Aug 20, 2013, at 1:28 PM, Matt Bridges <notifications@github.com<mailto:notifications@github.com>> wrote:

Fair enough. Is this worth closing, then?

**Comment by bf4** [comment]
Not just a bot, a good practice :)

**Comment by joshuaflanagan** [comment]
@bf4 :smile: i want the next version of your bot to submit a pull request!

**Comment by bf4** [comment]
I take PR's :) ([or will do that eventually](https://github.com/bf4/gemproject/issues/5))

Ironically, if there were a script good enough at guessing the license for a project, rubygems.org might not need to rely on the gemspec.  

There's a number of issues to consider, though there may be some mvp.
1. Is there a license file (accommodate spelling variants), and if so which license is it (match against known licenses)
2. Scrape the README for possible licenses
3. Figure out which file to change, the gemspec, the Rakefile, a custom gem task?
4. Determine if that change has already been made, but is unreleased
5. Handle multiple licenses
6. Tweaking the changes in the PR would now be dependent on my branch
7. I would end of forking quite a few repos!

**Comment by bf4** [comment]
Awesome, thanks! :rainbow:
