### ISSUE TITLE
Prep for Resque fork and Pull Request

### ISSUE THREAD

**Issue by mdespuits** [PeopleAdmin/resque-clues#6]
Due to the need to monkey patch Resque, `resque-clues` is not quite ready for release as a general plugin for the community to consume and use. Here are the pieces of the puzzle still necessary for this push.
- [ ] Fork `resque` to `PeopleAdmin/resque`
- [ ] Setup new fork to support our "monkey-patch" in a more idiomatic way
- [ ] Remove monkey patch from `resque-clues`
- [ ] Send Pull Request to Resque to support the setup for this plugin.
- [ ] On Pull Request merge, point to master Resque gem and have :cake:

**Comment by joshuaflanagan** [comment]
We need to comment on https://github.com/resque/resque/issues/552 regarding our metadata needs.

**Comment by billeisenhauer** [comment]
Is this still an issue?

**Comment by mdespuits** [comment]
@joshuaflanagan You have a better idea of what `resque-clues`'s metadata needs are. From the discussion in the PR you referenced, it sounds like they are introducing a separate gem for adding metadata to Resque jobs. Would that be a better path for this?
