### ISSUE TITLE
graphs?

### ISSUE THREAD

**Issue by mcfiredrill** [PeopleAdmin/resque-clues#7]
Your graphs in the readme are quite nice. :heart: What did you use to make them? :)

**Comment by mdespuits** [comment]
We use Splunk to monitor our app, and the graphs are the result of Splunk queries

**Comment by mcfiredrill** [comment]
Thanks!

**Comment by jjasghar** [comment]
If you want to play around with it there is a free tier, http://www.splunk.com/view/free-vs-enterprise/SP-CAAAE8W with 500 MBs per day of indexing.
